server:
  port: 8889

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: hello
          uri: lb://consumer
          predicates:
            - Path=/consumer/**    # 断言：路径相匹配的进行路由
        - id: security
          uri: lb://security
          predicates:
            - Path=/security/**
          filters:
            - StripPrefix=1 # 断言前缀取消的层数
    nacos:
      discovery:
        server-addr: localhost:8848


